services:

  postgres:
    image: postgres:16
    container_name: ${DB_HOST}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - 5432:5432

  app:
    build:
      context: .
      dockerfile: ./src/tactical_empathy/Dockerfile
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
      - ${APP_PORT}:8000
    environment:
      - DJANGO_SETTINGS_MODULE=tactical_empathy.settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_NAME=${POSTGRES_DB}
    depends_on:
      postgres:
        condition: service_healthy